repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
      - id: flake8
      - id: mixed-line-ending
        args:
          - --fix=no
      - id: no-commit-to-branch
        args:
          - --branch=master
      - id: trailing-whitespace

  - repo: https://github.com/mwouts/jupytext
    rev: v1.13.4
    hooks:
      - id: jupytext
        args: [--sync]
