name: Build release version

on:
  push:
    tags:
      - '*.*.*'
  pull_request:
    branches:
      master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: pip install -e ".[ci]"

      - name: Build release artifacts
        run: python -m build

      - name: Publish PR builds to pypi test mirror
        if: ${{ startsWith(github.ref, 'refs/tags/') }} != true
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish tag to pypi
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
