name: Build documentation

on:
  pull_request:
    branches:
      master
  push:
    branches:
      master

jobs:
  build-matrix:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate version matrix
        id: build-matrix
        run: echo '::set-output name=versions::["stable", "latest"]'
    outputs:
      versions: ${{ steps.build-matrix.outputs.versions }}

  docs:
    runs-on: ubuntu-20.04
    needs: build-matrix
    strategy:
      # Make sure we never build docs in parallel in case we deploy new
      # versions to avoid potential race conditions while pushing to gh pages.
      max-parallel: 1
      matrix:
        version: ${{ fromJSON(needs.build-matrix.outputs.versions) }}
    steps:
      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout target
        run: |
          if ${{ matrix.version == 'latest' }}; then
            git checkout ${{ github.sha }}
          elif ${{ matrix.version == 'stable' }}; then
            git checkout tags/$(git tag | sort -V | tail -1)
          else
            git checkout ${{ matrix.version }}
          fi

      - name: Generate version list
        run: |
          echo ${{ needs.build-matrix.outputs.versions }} > doc_versions.json

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          pip install -r requirements/ci.txt
          pip install \
            -r requirements/docs.txt \
            -r requirements/base.txt \
            -r requirements/dev.txt

      - name: Run doctests
        run: PYTHONPATH=. sphinx-build -b doctest docs $(mktemp -d)

      - name: Build docs
        run: |
          PYTHONPATH=. sphinx-build \
            -b html \
            -D version=${{ matrix.version }} \
            -D release=${{ matrix.version }} \
            docs \
            website/docs/${{ matrix.version }}

      - name: Publish documentation
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: pymanopt/pymanopt.github.io
          publish_branch: main
          publish_dir: website/docs/${{ matrix.version }}
          destination_dir: docs/${{ matrix.version }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
