name: Deploy new version

on:
  push:
    tags:
      - "*"
    inputs:
      repository: pypi

  workflow_dispatch:
    inputs:
      repository:
        description: test.pypi or pypi
        required: false
        default: test.pypi

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          pip install pip==21.3.1 setuptools==47.1.0 wheel==0.37.0
          pip install -r requirements/dev.txt

      - name: Build sdist and wheel
        run: python setup.py sdist bdist_wheel

      - name: Publish to pypi
        if: ${{ github.event.inputs.repository == pypi }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish to test.pypi
        if: ${{ github.event.inputs.repository = test.pypi }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
